mysql:
  image: orchardup/mysql
redis:
  image: redis
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/miaoapp
  ports:
    - "3000:3000"
  links:
    - mysql
    - redis