source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use mysql as the database for Active Record
gem 'mysql2'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.2'
# gem 'rack-cors'
# gem 'rails-api'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# image upload and magick
gem 'carrierwave'
gem 'mini_magick'

gem 'kaminari'

gem 'active_model_serializers'

gem 'acts_as_follower'

gem 'validate_url'

# gem 'exception_notification'
# gem 'unread'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'brakeman', require: false
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
  # https://github.com/rdoc/rdoc
  gem 'rdoc'
end
